#fixRake: Needs to be either -1 (meaning it is not fixed andcan be set for individual tables),
#or a value of 0 or above, fixing the rake to that value and preventing it from being changed by any table
options:
  general:
    autoUpdate: true
    cleanupOnDisable: true
    disableCommandsWhilePlaying: false
    preventMovementOutsideChatRange: true
  log:
    enableLog: false
    dateFormat: 'dd/MM/yyyy HH:mm:ss'
  chat:
    displayTag: true
    colorTag: '&1'
    colorNormalMessage: '&f'
    colorErrorMessage: '&c'
    colorHighlight: '&6'
  generalDefaults:
    allowRebuys: true
    displayTurnsPublicly: false
    autoStart: 0
    minBuy: 0
    maxBuy: 100000
    publicChatRange: 30
    turnSeconds: 60
    autoKickOnLeave: false
  poker:
    fixRake: -1
    defaults:
      minRaiseIsAlwaysBB: true
      sb: 500
      bb: 1000
      ante: 0
      dynamicFrequency: 0
      rake: 0.0
      minRaise: 200
  blackjack:
    defaults:
      allowDoubleDown: true
      minBet: 100
      amountOfDecks: 5